# Generated by Django 3.1.1 on 2021-05-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
