# Generated by Django 3.1.1 on 2021-05-16 08:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(default=0)),
                ('order_total', models.IntegerField(default=100)),
                ('payment_mode', models.CharField(choices=[('ONLINE_PAY', 'Online Payment'), ('COD_PAY', 'Cash Payment')], default='Cash Payment', max_length=30)),
                ('products', models.TextField(default='')),
                ('address', models.CharField(default='', max_length=20)),
                ('order_completed', models.BooleanField(default=False)),
                ('date_of_ordering', models.DateField(default=datetime.date.today)),
                ('date_of_delivery', models.DateField(default=datetime.date(2021, 5, 23))),
                ('order_placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
